spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortener_subs?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: SubsServiceConnectionPool
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false
    show-sql: false
  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      host: 127.0.0.1
      port: 6379

kafka:
  payment:
    topic:
      name: urlshortener-payment-events

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/