spring:
  application:
    name: urlshortener-subscription-service
  profiles:
    active: dev

server:
  port: 9099

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
