spring:
  application:
    name: urlshortener-subscription-service
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${spring.application.instance_id:${random.value}}
        register: true
        fail-fast: true
        enabled: true
        prefer-ip-address: true
        catalog-services-watch-delay: 30000
        health-check-interval: 30s
        register-health-check: off
        health-check-path: /admin/management/health
        heartbeat:
          reregister-service-on-failure: true

server:
  port: 9099

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
      base-path: /admin/management
  endpoint:
    health:
      show-details: always
    info:
      access: read_only
    metrics:
      access: read_only

ui:
  dashboard:
    url: http://localhost:3000/dashboard

subscription:
  notification:
    default-logo-url: https://res.cloudinary.com/dmdbqq7fp/bysb90sd8dsjst6ieeno.png
  packs:
    initializer:
      push-default-packs-to-database: true